#!/bin/sh

set -e
set -o pipefail

## Define ZONE in /etc/dollarupdate
source "/etc/dollarupdate"

ZF="$(mktemp)"

dig +onesoa @127.0.0.1 -k /etc/named/transfer-ext.key "$ZONE". AXFR | \
/usr/local/bin/simplifyzone >"$ZF"

/usr/local/bin/dollarupdate "$ZF"

rm "$ZF"
